### ISSUE TITLE
Get 100% unit test coverage on redux selectors

### ISSUE THREAD

**Issue by schoinh** [allen-cell-animated/simularium-website#182]
## What needs to happen?
Check if all the selector functions have test coverage. If not, write more tests.

## Why should we do this?
We rely on selectors for most of the data handling/manipulation in this repo, so they need to be rock solid.

## When does this need to get done?
Ideally in the next month or so? Would be easier with Jest and its coverage reporting in place

**Comment by meganrm** [comment]
A thing I just realized that I should have thought of before, but the basic selectors are a lot of these files and we don't want to test them. One solution if we really want to enforce 100% is to break the files up into basic selectors and composed selectors and enforce 100% on composed. we could structure it so that everything still gets exported from `selectors/index` so we wouldn't have to change the import statements in the other files. 
```
selectors/
     index <-- exports composed and basic
     basic
     composed```

**Comment by meganrm** [comment]
Alternatively, jest does as an ignore next: `/* istanbul ignore next */` but you would have to add it before each basic selector. They don't have a "open ignore" "close ignore" as far as I can tell.
