### ISSUE TITLE
replace "dev" with "development"

### ISSUE THREAD

**Issue by meganrm** [allen-cell-animated/simularium-website#188]
## What needs to happen?
Any instance of "dev" is changed to "development"

## Why should we do this?
webpack uses "development" as a keyword, but we have "dev" as our own variable, and it just seems unnecessarily confusing 

## When does this need to get done?
No time line

**Comment by toloudis** [comment]
But Webpack doesn't support a `staging` mode.  I basically have no problem using `dev` or `development` but conforming to webpack is not necessarily going to solve the staging part.  Do they let you define your own modes?

**Comment by schoinh** [comment]
> But Webpack doesn't support a `staging` mode. I basically have no problem using `dev` or `development` but conforming to webpack is not necessarily going to solve the staging part. Do they let you define your own modes?

Sorry, what does staging have to do with this issue? I'm confused now 😆

**Comment by toloudis** [comment]
I know I'm probably overthinking this, but:

We usually talk about 3 different build/deploy configurations for AICS software: dev(development), stg(staging), and prod(production).   Webpack has modes `development` and `production` but they don't include a staging mode. 

 I'm just saying we should make sure we are not diverging away from general AICS deployment practices, so that our stuff is able to plug in to any devops deployment tooling.

**Comment by meganrm** [comment]
Maybe this isn't important to do. I just know there was some issue in CFE where a script was expecting "development" but the "dev" var got sent in, and I thought it was easier to just use the word most packages use instead of keeping track. It might have been in either the gradle or Jenkins file, so it might not matter anymore.

**Comment by schoinh** [comment]
Uncertain priority / scope, closing for now
